spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml